modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"

[[mods]]
modId = "differentiate"
version = "${version}"
displayName = "Differentiate"
authors = "EltrutLikes, StevenPlayzz"
description = '''
Core mod for all of the Eltrut & Co. Mods!
'''
#logoFile = ""

[[dependencies.differentiate]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.differentiate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"