modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Eltrut-Co/Differentiate/issues"
[[mods]]
modId="differentiate"
version="1.0.1"
displayName="Differentiate"
logoFile="differentiate.png"
credits="EltrutLikes"
authors="Eltrut & Co."
description='''
'''

[[dependencies.differentiate]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.differentiate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"