modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Eltrut-Co/Differentiate/issues"
[[mods]]
modId="differentiate"
version="1.0.3"
displayName="Differentiate"
logoFile="differentiate.png"
credits="EltrutLikes, Steven"
authors="Eltrut & Co."
description='''
'''

[[dependencies.differentiate]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.differentiate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"