modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Eltrut-Co/Differentiate/issues"
[[mods]]
modId="differentiate"
version="0.5.3"
displayName="Differentiate"
logoFile="differentiate.png"
credits="EltrutLikes"
authors="Eltrut & Co."
description='''
'''

[[dependencies.differentiate]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.differentiate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"