modLoader="javafml"
loaderVersion="[2,)"
license="CC BY-NC-SA 3.0 Unported"
issueTrackerURL="https://github.com/Eltrut-Co/Differentiate/issues"
[[mods]]
modId="differentiate"
version="3.0.0"
displayName="Differentiate"
logoFile="differentiate.png"
credits="EltrutLikes"
authors="Eltrut & Co."
description='''
'''

[[dependencies.differentiate]]
    modId="neoforge"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.differentiate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"